# Generated by Django 3.1.4 on 2020-12-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20201204_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='language',
            field=models.CharField(choices=[('e', 'English'), ('u', 'Ukrainian'), ('p', 'Polish')], default='English', max_length=100),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='style',
            field=models.CharField(choices=[('f', 'Formal'), ('i', 'Informal')], default='Formal', max_length=100),
        ),
    ]
